services:
  supplier-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supplier-api
    ports:
      - "3001:3000"
    environment:
      - DATABASE_URL=postgresql://hermel:h33r%23M91@host.docker.internal:5001/requisiciones
      - JWT_SECRET=DclTLrmSKHFovBCUvVflWTNg1ZnlCXDXhM1Pr5QuEVZ
    restart: always
