services:
  supplier-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supplier-api
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=hermeldb # Cambia según tu configuración
      - DB_PORT=5001
      - DB_USERNAME=hermel
      - DB_PASSWORD="h33r#M91"
      - DB_DATABASE=requisiciones
      - JWT_SECRET=DclTLrmSKHFovBCUvVflWTNg1ZnlCXDXhM1Pr5QuEVZ
    restart: always
